
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    language: vi

# Example configuration.yaml entry configuring Google Assistant
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - cover


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switchs/
cover: !include_dir_merge_list cover/
binary_sensor: !include_dir_merge_list binary_sensor/

camera:
  - platform: mjpeg
    mjpeg_url: http://localhost:8081/?action=stream


notify:
  - name: home
    platform: pushbullet
    api_key: o.9gtbXpC1gdtRhD1RWW4nsIfw05cdsvmm

